FROM python:3.11-slim
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -qq && \
    apt-get install -y -qq iproute2 iputils-ping net-tools && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
CMD ["python3"]
