FROM ubuntu:22.04
RUN apt-get update -qq && \
    apt-get install -y -qq wireguard-tools iptables iproute2 iputils-ping net-tools && \
    apt-get clean && rm -rf /var/lib/apt/lists/*
CMD ["/bin/bash"]
