[Interface]
PrivateKey = GOtvRQw0GH1h6RhRPS/yfMUcIewvz1qUunzVDiPSgmQ=
Address = 10.10.1.1/24
ListenPort = 51820
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -A FORWARD -i eth1 -j ACCEPT; iptables -A FORWARD -o eth1 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -D FORWARD -i eth1 -j ACCEPT; iptables -D FORWARD -o eth1 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = TSRmteDUnWnClpdbW9IJTKg6TM0gfHmI9Wxcp3sL8Vs=
AllowedIPs = 10.10.1.10/32, 192.168.10.0/24

[Peer]
PublicKey = +KwjbqQsV17Pt5pQVblf3qdpDlPaq8mnTcgTVbtegjM=
AllowedIPs = 10.10.1.11/32, 192.168.11.0/24

[Peer]
PublicKey = ihcAWKctt4MHgJposMDSDNwjK1otKdNxNDEtB0WXQ1o=
AllowedIPs = 10.10.1.20/32, 192.168.20.0/24
