[Interface]
PrivateKey = kA17lu/m8SjYDrHhj9Gg4dFf8XQHCWzEHBLFr1QOTkA=
Address = 10.10.1.1/24
ListenPort = 51820
PostUp = iptables -A FORWARD -i wg0 -j ACCEPT; iptables -A FORWARD -o wg0 -j ACCEPT; iptables -A FORWARD -i eth1 -j ACCEPT; iptables -A FORWARD -o eth1 -j ACCEPT; iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
PostDown = iptables -D FORWARD -i wg0 -j ACCEPT; iptables -D FORWARD -o wg0 -j ACCEPT; iptables -D FORWARD -i eth1 -j ACCEPT; iptables -D FORWARD -o eth1 -j ACCEPT; iptables -t nat -D POSTROUTING -o eth0 -j MASQUERADE

[Peer]
PublicKey = zQxQndz9y/iRySc9+W5SNTidnwY23TGGxzmaChvbiRc=
AllowedIPs = 10.10.1.10/32, 192.168.10.0/24

[Peer]
PublicKey = zNzs3ytrJIOMG2LEf9BJnV6AMFF1eqIGvL8cIYcw5Vg=
AllowedIPs = 10.10.1.11/32, 192.168.11.0/24

[Peer]
PublicKey = knFeyki2QsG+SIl9pXlz5b7CafidyPpwjWHFSD59ixU=
AllowedIPs = 10.10.1.20/32, 192.168.20.0/24
